name: Create Table

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compute:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      # we want a lower-case version of the repo name
      - name: Sanitize repo slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ github.repo.repo }}'.toLowerCase()
      -  name: Compute
         uses: addnab/docker-run-action@v3
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_slug.outputs.result }}:latest
            options: -v ${{ github.workspace }}:/home/rstudio 
            run: |
              Rscript "programs/master.R"
         #run: "bash -x ./run_locally.sh latest ${{ secrets.DOCKERHUB_USERNAME }}"
      # send it to the results branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: .
           user_name: 'Github Action Bot'
           user_email: 'lars.vilhuber@cornell.edu'
           publish_branch: results 
           keep_files: true
